#!/usr/bin/env bash

set -e

curl -L -o nekoray.deb  "https://github.com/Mahdi-zarei/nekoray/releases/download/4.2.9/nekoray-4.2.9-2025-01-20-debian-x64.deb"


sudo dpkg -i nekoray.deb

sudo apt-get install -f -y

rm nekoray.deb

bash <(curl -fsSL https://raw.githubusercontent.com/amir1376/ab-download-manager/master/scripts/install.sh)
